### ISSUE TITLE
java.lang.NumberFormatException: Invalid int: "average"

### ISSUE THREAD

**Issue by e-yes** [woodenshark/prismatik-for-android#49] opened 2014-12-20 15:01 UTC
``` bash
java.lang.Error: FATAL EXCEPTION [Timer-7]
Unity version     : 4.5.2f1
Device model      : eweat ew902
Device fingerprint: eweat/rtk_phoenix/phoenix:4.4/KRT16O/eng.tony.20141212.174301:eng/test-keys

Caused by: java.lang.NumberFormatException: Invalid int: "average"
at java.lang.Integer.invalidInt(Integer.java:137)
at java.lang.Integer.parse(Integer.java:374)
at java.lang.Integer.parseInt(Integer.java:365)
at com.woodenshark.prismatik.mode.ModeController_Capturing.takeColors(ModeController_Capturing.java:278)
at com.woodenshark.prismatik.mode.ModeController_Capturing$3.run(ModeController_Capturing.java:208)
at java.util.Timer$TimerImpl.run(Timer.java:284)

```

**Comment by chris-tina** [comment] 2014-12-21 22:25
duplicate of issue #37

**Closed as completed by chris-tina** 2014-12-21 22:25 UTC
Labels: Android, SplunkMINT, App versions: 0.40
